<?php

declare(strict_types=1);

/**
 * @return list<string> Two-line exam wishes (line break between).
 */
function trytest_exam_wishes_two_line_pool(): array
{
    return [
        "Believe in yourself.\nYou are ready.",
        "Stay calm.\nDo your best.",
        "Trust your work.\nYou've got this.",
        "Keep focused.\nSuccess will follow.",
        "Stay confident.\nYou can do it.",
        "Work hard.\nFinish strong.",
        "Stay positive.\nKeep going.",
        "Be calm.\nThink clearly.",
        "Do your best.\nThat is enough.",
        "Stay strong.\nYou'll succeed.",
        "Keep trying.\nDon't give up.",
        "Stay focused.\nYou are capable.",
        "Believe always.\nAchieve today.",
        "Stay calm.\nYou are prepared.",
        "Keep steady.\nDo your best.",
        "Stay confident.\nTrust yourself.",
        "Stay sharp.\nFinish well.",
        "Keep going.\nYou're close.",
        "Stay relaxed.\nThink clearly.",
        "Stay strong.\nYou'll do great.",
        "Keep calm.\nStay focused.",
        "Work smart.\nShine bright.",
        "Believe more.\nFear less.",
        "Stay ready.\nDo well.",
        "Stay steady.\nKeep moving.",
        "Trust yourself.\nStay calm.",
        "Stay focused.\nKeep pushing.",
        "Stay positive.\nDo your best.",
        "Keep believing.\nYou'll succeed.",
        "Stay calm.\nStay confident.",
        "Keep it simple.\nDo your best.",
        "Stay strong.\nStay focused.",
        "Work hard.\nStay calm.",
        "Stay determined.\nFinish strong.",
        "Believe in you.\nAlways.",
        "Stay calm.\nTrust the process.",
        "Keep your focus.\nDo well.",
        "Stay relaxed.\nStay sharp.",
        "Stay positive.\nStay strong.",
        "You are ready.\nGo succeed.",
        "Stay calm.\nStay focused.",
        "Keep going.\nDon't stop.",
        "Stay strong.\nDo your best.",
        "Believe always.\nWin today.",
        "Keep trying.\nStay focused.",
        "Stay calm.\nThink smart.",
        "Stay ready.\nStay steady.",
        "Trust yourself.\nYou can.",
        "Stay focused.\nStay confident.",
        "Stay positive.\nStay calm.",
        "Keep going.\nYou're doing well.",
        "Stay calm.\nFinish strong.",
        "Believe in yourself.\nStay focused.",
        "Stay steady.\nStay strong.",
        "Keep pushing.\nYou'll succeed.",
        "Stay positive.\nKeep moving.",
        "Trust your effort.\nDo well.",
        "Stay calm.\nDo great.",
        "Stay focused.\nStay steady.",
        "Keep trying.\nStay confident.",
        "Stay strong.\nStay positive.",
        "Stay calm.\nTrust yourself.",
        "Believe more.\nAchieve more.",
        "Stay focused.\nKeep winning.",
        "Stay steady.\nKeep calm.",
        "Stay calm.\nStay sharp.",
        "Keep going.\nStay focused.",
        "Stay strong.\nFinish well.",
        "Stay confident.\nDo great.",
        "Keep pushing.\nStay calm.",
        "Stay positive.\nStay ready.",
        "Keep calm.\nStay strong.",
        "Believe in success.\nWork for it.",
        "Stay focused.\nStay calm.",
        "Stay strong.\nStay determined.",
        "Stay calm.\nYou can do it.",
        "Keep trying.\nStay positive.",
        "Stay ready.\nStay focused.",
        "Stay steady.\nStay confident.",
        "Stay calm.\nStay strong.",
        "Keep moving.\nStay focused.",
        "Stay positive.\nStay steady.",
        "Stay calm.\nStay ready.",
        "Keep going.\nStay strong.",
        "Stay focused.\nStay sharp.",
        "Stay calm.\nStay confident.",
        "Keep pushing.\nStay focused.",
        "Stay strong.\nStay ready.",
        "Stay calm.\nStay positive.",
        "Stay steady.\nStay calm.",
        "Believe always.\nStay strong.",
        "Stay focused.\nStay calm.",
        "Keep going.\nStay positive.",
        "Stay ready.\nStay steady.",
        "Stay calm.\nStay focused.",
        "Keep trying.\nStay strong.",
        "Stay confident.\nStay calm.",
        "Stay focused.\nStay ready.",
        "Stay steady.\nStay strong.",
        "Stay calm.\nStay confident.",
        "Stay positive.\nStay focused.",
        "Stay calm.\nKeep going.",
        "Stay strong.\nStay focused.",
        "Keep trying.\nStay calm.",
        "Stay steady.\nStay positive.",
        "Stay calm.\nStay strong.",
        "Keep going.\nStay ready.",
        "Stay focused.\nStay steady.",
        "Stay calm.\nStay positive.",
        "Stay strong.\nStay calm.",
        "Stay focused.\nStay ready.",
        "Stay steady.\nStay calm.",
        "Stay positive.\nStay strong.",
        "Stay calm.\nStay focused.",
        "Stay ready.\nStay steady.",
        "Stay strong.\nStay positive.",
        "Stay calm.\nStay ready.",
        "Stay focused.\nStay strong.",
        "Stay steady.\nStay focused.",
        "Stay calm.\nStay strong.",
        "Keep going.\nStay calm.",
        "Stay positive.\nStay ready.",
        "Stay focused.\nStay calm.",
        "Stay strong.\nStay steady.",
        "Stay calm.\nStay focused.",
        "Keep trying.\nStay strong.",
        "Stay ready.\nStay calm.",
        "Stay steady.\nStay positive.",
        "Stay focused.\nStay strong.",
        "Stay calm.\nStay steady.",
        "Stay strong.\nStay calm.",
        "Stay focused.\nStay ready.",
        "Stay steady.\nStay calm.",
        "Stay positive.\nStay focused.",
        "Stay calm.\nStay strong.",
        "Keep going.\nStay steady.",
        "Stay focused.\nStay calm.",
        "Stay strong.\nStay ready.",
        "Stay calm.\nStay focused.",
        "Stay steady.\nStay strong.",
        "Stay positive.\nStay calm.",
        "Stay focused.\nStay steady.",
        "Stay calm.\nStay strong.",
        "Stay ready.\nStay focused.",
        "Stay steady.\nStay calm.",
        "Stay strong.\nStay positive.",
        "Stay calm.\nStay focused.",
        "Stay ready.\nStay steady.",
        "Stay focused.\nStay calm.",
        "Stay strong.\nStay steady.",
        "Stay calm.\nStay focused.",
        "Stay strong.\nStay ready.",
        "Stay steady.\nStay positive.",
        "Stay calm.\nStay strong.",
        "Stay focused.\nStay steady.",
        "Stay ready.\nStay calm.",
        "Stay positive.\nStay strong.",
        "Stay calm.\nStay focused.",
        "Stay steady.\nStay ready.",
        "Stay strong.\nStay calm.",
        "Stay focused.\nStay steady.",
        "Stay calm.\nStay strong.",
        "Stay ready.\nStay positive.",
        "Stay steady.\nStay calm.",
        "Stay strong.\nStay focused.",
        "Stay calm.\nStay ready.",
        "Stay positive.\nStay steady.",
        "Stay focused.\nStay calm.",
        "Stay strong.\nStay ready.",
        "Stay steady.\nStay calm.",
        "Stay calm.\nStay focused.",
        "Stay strong.\nStay steady.",
        "Stay ready.\nStay calm.",
        "Stay positive.\nStay focused.",
        "Stay calm.\nStay strong.",
        "Stay steady.\nStay ready.",
        "Stay focused.\nStay calm.",
        "Stay strong.\nStay positive.",
        "Stay calm.\nStay steady.",
        "Stay ready.\nStay focused.",
        "Stay strong.\nStay calm.",
        "Stay focused.\nStay steady.",
        "Stay calm.\nStay positive.",
        "Stay ready.\nStay strong.",
        "Stay steady.\nStay calm.",
        "Stay focused.\nStay strong.",
        "Stay calm.\nStay ready.",
        "Stay positive.\nStay steady.",
        "Stay strong.\nStay calm.",
        "Stay focused.\nStay ready.",
        "Stay steady.\nStay calm.",
        "Stay strong.\nStay focused.",
        "Stay calm.\nStay positive.",
        "Stay ready.\nStay steady.",
        "Stay focused.\nStay calm.",
        "Stay strong.\nStay ready.",
        "Stay calm.\nStay steady.",
        "Stay positive.\nStay strong.",
        "Stay focused.\nStay calm.",
        "Stay strong.\nYou'll succeed.",
    ];
}
