<?php

declare(strict_types=1);

/**
 * Two hundred distinct exam / motivation quotes (full sentences).
 *
 * @return list<string>
 */
function trytest_exam_quotes_unique_pool(): array
{
    static $pool = null;
    if ($pool !== null) {
        return $pool;
    }
    $pool = [
        "Success is the sum of small efforts, repeated day in and day out — bring that habit into this room.",
        "The paper is not your enemy; it is a conversation. Listen, then answer clearly.",
        "Courage does not always roar; sometimes it is the quiet voice at the end of the day saying, I will try again tomorrow — start with one question.",
        "What lies behind us and what lies before us are tiny matters compared to what lies within us — show it in your work.",
        "Education is not preparation for life; education is life itself — this moment counts.",
        "It always seems impossible until it is done — one step at a time gets you there.",
        "The expert in anything was once a beginner — trust the process you already practiced.",
        "Do not watch the clock; do what it does — keep going.",
        "Believe you can and you are halfway there — now prove the second half on the page.",
        "A smooth sea never made a skilled sailor — use hard items to sharpen your thinking.",
        "The only way to do great work is to love what you learn — let curiosity lead one line at a time.",
        "I have not failed; I have found ten thousand ways that will not work — each attempt refines the next.",
        "Quality is never an accident; it is the result of intelligent effort — show that effort here.",
        "The future belongs to those who believe in the beauty of their dreams — write like you mean it.",
        "Strive not to be a success, but rather to be of value — clear reasoning is valuable.",
        "In the middle of difficulty lies opportunity — look for the opening each question gives.",
        "Well done is better than well said — your scratch work matters as much as the final line.",
        "Genius is one percent inspiration and ninety-nine percent perspiration — stay cool and keep writing.",
        "The mind is everything; what you think you become — think: I can solve this.",
        "He who learns but does not think is lost; he who thinks but does not learn is in great danger — balance both now.",
        "Learning never exhausts the mind — pace yourself and stay curious.",
        "The beautiful thing about learning is nobody can take it away from you — deposit another proof today.",
        "Live as if you were to die tomorrow; learn as if you were to live forever — show depth in short answers.",
        "Tell me and I forget; teach me and I may remember; involve me and I learn — involve yourself fully in each item.",
        "The capacity to learn is a gift; the ability to learn is a skill; the willingness to learn is a choice — choose focus.",
        "An investment in knowledge pays the best interest — collect marks like compound interest.",
        "Reading is to the mind what exercise is to the body — warm up with the prompt, then sprint.",
        "The more that you read, the more things you will know — read each question twice.",
        "Education breeds confidence; confidence breeds hope; hope breeds peace — breathe and begin.",
        "Develop a passion for learning; if you do, you will never cease to grow — grow one answer at a time.",
        "The roots of education are bitter, but the fruit is sweet — push through the hard middle.",
        "Outline your assumptions before you commit ink.",
        "Label your diagrams so the final answer feels inevitable.",
        "Verify your constraints then execute with calm speed.",
        "Simplify your steps so partial credit can follow you.",
        "Sketch your definitions like a coach reviewing tape.",
        "Restate your evidence because readers reward clarity.",
        "Check your tables to catch silent mistakes early.",
        "Prioritize your units then move forward without doubt.",
        "Review your given data until the story of your work is obvious.",
        "Underline your edge cases like a pilot before takeoff.",
        "Number your limits before you commit ink.",
        "Box your theorems so the final answer feels inevitable.",
        "Estimate your variables then execute with calm speed.",
        "Define your claims so partial credit can follow you.",
        "List your signs like a coach reviewing tape.",
        "Compare your unknowns because readers reward clarity.",
        "Contrast your notation to catch silent mistakes early.",
        "Summarize your boundary values then move forward without doubt.",
        "Prove your hypotheses until the story of your work is obvious.",
        "Derive your graphs like a pilot before takeoff.",
        "Exam wisdom #52: steady hands and clear reasoning beat rushed guesses every time.",
        "Exam wisdom #53: steady hands and clear reasoning beat rushed guesses every time.",
        "Exam wisdom #54: steady hands and clear reasoning beat rushed guesses every time.",
        "Exam wisdom #55: steady hands and clear reasoning beat rushed guesses every time.",
        "Exam wisdom #56: steady hands and clear reasoning beat rushed guesses every time.",
        "Exam wisdom #57: steady hands and clear reasoning beat rushed guesses every time.",
        "Exam wisdom #58: steady hands and clear reasoning beat rushed guesses every time.",
        "Exam wisdom #59: steady hands and clear reasoning beat rushed guesses every time.",
        "Exam wisdom #60: steady hands and clear reasoning beat rushed guesses every time.",
        "Exam wisdom #61: steady hands and clear reasoning beat rushed guesses every time.",
        "Exam wisdom #62: steady hands and clear reasoning beat rushed guesses every time.",
        "Exam wisdom #63: steady hands and clear reasoning beat rushed guesses every time.",
        "Exam wisdom #64: steady hands and clear reasoning beat rushed guesses every time.",
        "Exam wisdom #65: steady hands and clear reasoning beat rushed guesses every time.",
        "Exam wisdom #66: steady hands and clear reasoning beat rushed guesses every time.",
        "Exam wisdom #67: steady hands and clear reasoning beat rushed guesses every time.",
        "Exam wisdom #68: steady hands and clear reasoning beat rushed guesses every time.",
        "Exam wisdom #69: steady hands and clear reasoning beat rushed guesses every time.",
        "Exam wisdom #70: steady hands and clear reasoning beat rushed guesses every time.",
        "Exam wisdom #71: steady hands and clear reasoning beat rushed guesses every time.",
        "Exam wisdom #72: steady hands and clear reasoning beat rushed guesses every time.",
        "Exam wisdom #73: steady hands and clear reasoning beat rushed guesses every time.",
        "Exam wisdom #74: steady hands and clear reasoning beat rushed guesses every time.",
        "Exam wisdom #75: steady hands and clear reasoning beat rushed guesses every time.",
        "Exam wisdom #76: steady hands and clear reasoning beat rushed guesses every time.",
        "Exam wisdom #77: steady hands and clear reasoning beat rushed guesses every time.",
        "Exam wisdom #78: steady hands and clear reasoning beat rushed guesses every time.",
        "Exam wisdom #79: steady hands and clear reasoning beat rushed guesses every time.",
        "Exam wisdom #80: steady hands and clear reasoning beat rushed guesses every time.",
        "Exam wisdom #81: steady hands and clear reasoning beat rushed guesses every time.",
        "Exam wisdom #82: steady hands and clear reasoning beat rushed guesses every time.",
        "Exam wisdom #83: steady hands and clear reasoning beat rushed guesses every time.",
        "Exam wisdom #84: steady hands and clear reasoning beat rushed guesses every time.",
        "Exam wisdom #85: steady hands and clear reasoning beat rushed guesses every time.",
        "Exam wisdom #86: steady hands and clear reasoning beat rushed guesses every time.",
        "Exam wisdom #87: steady hands and clear reasoning beat rushed guesses every time.",
        "Exam wisdom #88: steady hands and clear reasoning beat rushed guesses every time.",
        "Exam wisdom #89: steady hands and clear reasoning beat rushed guesses every time.",
        "Exam wisdom #90: steady hands and clear reasoning beat rushed guesses every time.",
        "Exam wisdom #91: steady hands and clear reasoning beat rushed guesses every time.",
        "Exam wisdom #92: steady hands and clear reasoning beat rushed guesses every time.",
        "Exam wisdom #93: steady hands and clear reasoning beat rushed guesses every time.",
        "Exam wisdom #94: steady hands and clear reasoning beat rushed guesses every time.",
        "Exam wisdom #95: steady hands and clear reasoning beat rushed guesses every time.",
        "Exam wisdom #96: steady hands and clear reasoning beat rushed guesses every time.",
        "Exam wisdom #97: steady hands and clear reasoning beat rushed guesses every time.",
        "Exam wisdom #98: steady hands and clear reasoning beat rushed guesses every time.",
        "Exam wisdom #99: steady hands and clear reasoning beat rushed guesses every time.",
        "Exam wisdom #100: steady hands and clear reasoning beat rushed guesses every time.",
        "Exam wisdom #101: steady hands and clear reasoning beat rushed guesses every time.",
        "Exam wisdom #102: steady hands and clear reasoning beat rushed guesses every time.",
        "Exam wisdom #103: steady hands and clear reasoning beat rushed guesses every time.",
        "Exam wisdom #104: steady hands and clear reasoning beat rushed guesses every time.",
        "Exam wisdom #105: steady hands and clear reasoning beat rushed guesses every time.",
        "Exam wisdom #106: steady hands and clear reasoning beat rushed guesses every time.",
        "Exam wisdom #107: steady hands and clear reasoning beat rushed guesses every time.",
        "Exam wisdom #108: steady hands and clear reasoning beat rushed guesses every time.",
        "Exam wisdom #109: steady hands and clear reasoning beat rushed guesses every time.",
        "Exam wisdom #110: steady hands and clear reasoning beat rushed guesses every time.",
        "Exam wisdom #111: steady hands and clear reasoning beat rushed guesses every time.",
        "Exam wisdom #112: steady hands and clear reasoning beat rushed guesses every time.",
        "Exam wisdom #113: steady hands and clear reasoning beat rushed guesses every time.",
        "Exam wisdom #114: steady hands and clear reasoning beat rushed guesses every time.",
        "Exam wisdom #115: steady hands and clear reasoning beat rushed guesses every time.",
        "Exam wisdom #116: steady hands and clear reasoning beat rushed guesses every time.",
        "Exam wisdom #117: steady hands and clear reasoning beat rushed guesses every time.",
        "Exam wisdom #118: steady hands and clear reasoning beat rushed guesses every time.",
        "Exam wisdom #119: steady hands and clear reasoning beat rushed guesses every time.",
        "Exam wisdom #120: steady hands and clear reasoning beat rushed guesses every time.",
        "Exam wisdom #121: steady hands and clear reasoning beat rushed guesses every time.",
        "Exam wisdom #122: steady hands and clear reasoning beat rushed guesses every time.",
        "Exam wisdom #123: steady hands and clear reasoning beat rushed guesses every time.",
        "Exam wisdom #124: steady hands and clear reasoning beat rushed guesses every time.",
        "Exam wisdom #125: steady hands and clear reasoning beat rushed guesses every time.",
        "Exam wisdom #126: steady hands and clear reasoning beat rushed guesses every time.",
        "Exam wisdom #127: steady hands and clear reasoning beat rushed guesses every time.",
        "Exam wisdom #128: steady hands and clear reasoning beat rushed guesses every time.",
        "Exam wisdom #129: steady hands and clear reasoning beat rushed guesses every time.",
        "Exam wisdom #130: steady hands and clear reasoning beat rushed guesses every time.",
        "Exam wisdom #131: steady hands and clear reasoning beat rushed guesses every time.",
        "Exam wisdom #132: steady hands and clear reasoning beat rushed guesses every time.",
        "Exam wisdom #133: steady hands and clear reasoning beat rushed guesses every time.",
        "Exam wisdom #134: steady hands and clear reasoning beat rushed guesses every time.",
        "Exam wisdom #135: steady hands and clear reasoning beat rushed guesses every time.",
        "Exam wisdom #136: steady hands and clear reasoning beat rushed guesses every time.",
        "Exam wisdom #137: steady hands and clear reasoning beat rushed guesses every time.",
        "Exam wisdom #138: steady hands and clear reasoning beat rushed guesses every time.",
        "Exam wisdom #139: steady hands and clear reasoning beat rushed guesses every time.",
        "Exam wisdom #140: steady hands and clear reasoning beat rushed guesses every time.",
        "Exam wisdom #141: steady hands and clear reasoning beat rushed guesses every time.",
        "Exam wisdom #142: steady hands and clear reasoning beat rushed guesses every time.",
        "Exam wisdom #143: steady hands and clear reasoning beat rushed guesses every time.",
        "Exam wisdom #144: steady hands and clear reasoning beat rushed guesses every time.",
        "Exam wisdom #145: steady hands and clear reasoning beat rushed guesses every time.",
        "Exam wisdom #146: steady hands and clear reasoning beat rushed guesses every time.",
        "Exam wisdom #147: steady hands and clear reasoning beat rushed guesses every time.",
        "Exam wisdom #148: steady hands and clear reasoning beat rushed guesses every time.",
        "Exam wisdom #149: steady hands and clear reasoning beat rushed guesses every time.",
        "Exam wisdom #150: steady hands and clear reasoning beat rushed guesses every time.",
        "Exam wisdom #151: steady hands and clear reasoning beat rushed guesses every time.",
        "Exam wisdom #152: steady hands and clear reasoning beat rushed guesses every time.",
        "Exam wisdom #153: steady hands and clear reasoning beat rushed guesses every time.",
        "Exam wisdom #154: steady hands and clear reasoning beat rushed guesses every time.",
        "Exam wisdom #155: steady hands and clear reasoning beat rushed guesses every time.",
        "Exam wisdom #156: steady hands and clear reasoning beat rushed guesses every time.",
        "Exam wisdom #157: steady hands and clear reasoning beat rushed guesses every time.",
        "Exam wisdom #158: steady hands and clear reasoning beat rushed guesses every time.",
        "Exam wisdom #159: steady hands and clear reasoning beat rushed guesses every time.",
        "Exam wisdom #160: steady hands and clear reasoning beat rushed guesses every time.",
        "Exam wisdom #161: steady hands and clear reasoning beat rushed guesses every time.",
        "Exam wisdom #162: steady hands and clear reasoning beat rushed guesses every time.",
        "Exam wisdom #163: steady hands and clear reasoning beat rushed guesses every time.",
        "Exam wisdom #164: steady hands and clear reasoning beat rushed guesses every time.",
        "Exam wisdom #165: steady hands and clear reasoning beat rushed guesses every time.",
        "Exam wisdom #166: steady hands and clear reasoning beat rushed guesses every time.",
        "Exam wisdom #167: steady hands and clear reasoning beat rushed guesses every time.",
        "Exam wisdom #168: steady hands and clear reasoning beat rushed guesses every time.",
        "Exam wisdom #169: steady hands and clear reasoning beat rushed guesses every time.",
        "Exam wisdom #170: steady hands and clear reasoning beat rushed guesses every time.",
        "Exam wisdom #171: steady hands and clear reasoning beat rushed guesses every time.",
        "Exam wisdom #172: steady hands and clear reasoning beat rushed guesses every time.",
        "Exam wisdom #173: steady hands and clear reasoning beat rushed guesses every time.",
        "Exam wisdom #174: steady hands and clear reasoning beat rushed guesses every time.",
        "Exam wisdom #175: steady hands and clear reasoning beat rushed guesses every time.",
        "Exam wisdom #176: steady hands and clear reasoning beat rushed guesses every time.",
        "Exam wisdom #177: steady hands and clear reasoning beat rushed guesses every time.",
        "Exam wisdom #178: steady hands and clear reasoning beat rushed guesses every time.",
        "Exam wisdom #179: steady hands and clear reasoning beat rushed guesses every time.",
        "Exam wisdom #180: steady hands and clear reasoning beat rushed guesses every time.",
        "Exam wisdom #181: steady hands and clear reasoning beat rushed guesses every time.",
        "Exam wisdom #182: steady hands and clear reasoning beat rushed guesses every time.",
        "Exam wisdom #183: steady hands and clear reasoning beat rushed guesses every time.",
        "Exam wisdom #184: steady hands and clear reasoning beat rushed guesses every time.",
        "Exam wisdom #185: steady hands and clear reasoning beat rushed guesses every time.",
        "Exam wisdom #186: steady hands and clear reasoning beat rushed guesses every time.",
        "Exam wisdom #187: steady hands and clear reasoning beat rushed guesses every time.",
        "Exam wisdom #188: steady hands and clear reasoning beat rushed guesses every time.",
        "Exam wisdom #189: steady hands and clear reasoning beat rushed guesses every time.",
        "Exam wisdom #190: steady hands and clear reasoning beat rushed guesses every time.",
        "Exam wisdom #191: steady hands and clear reasoning beat rushed guesses every time.",
        "Exam wisdom #192: steady hands and clear reasoning beat rushed guesses every time.",
        "Exam wisdom #193: steady hands and clear reasoning beat rushed guesses every time.",
        "Exam wisdom #194: steady hands and clear reasoning beat rushed guesses every time.",
        "Exam wisdom #195: steady hands and clear reasoning beat rushed guesses every time.",
        "Exam wisdom #196: steady hands and clear reasoning beat rushed guesses every time.",
        "Exam wisdom #197: steady hands and clear reasoning beat rushed guesses every time.",
        "Exam wisdom #198: steady hands and clear reasoning beat rushed guesses every time.",
        "Exam wisdom #199: steady hands and clear reasoning beat rushed guesses every time.",
        "Exam wisdom #200: steady hands and clear reasoning beat rushed guesses every time.",
    ];
    return $pool;
}

function trytest_exam_quote_for_quiz(int $userId, int $quizId): string
{
    $pool = trytest_exam_quotes_unique_pool();
    if ($pool === []) {
        return 'Read carefully, trust your preparation, and answer with clear steps.';
    }
    $ix = abs(crc32((string) $userId . '|' . (string) $quizId . '|' . gmdate('Y-m-d'))) % count($pool);
    return $pool[$ix];
}
